### ISSUE TITLE
"Cannot find ".........\K.md"

### ISSUE THREAD

**Issue by KevinSoerensen** [Montapacking/AzureDevOpsWikiToDocFx#10]
I followed everything I could find in the docs to make this work but I always end up with "Cannot find <Path>\K.md because it does not exist"
What am I doing wrong here?

Azure Pipeline looks like this:

```
# run wiki
- task: AzureDevOpsWikiToDocFx@1
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/WebApi/DocFX/wiki'
    TargetFolder: '$(System.DefaultWorkingDirectory)/WebApi/DocFX/wikiTemp'
```

Any help would be appreciated
